name: MobHealth
main: me.sablednah.MobHealth.MobHealth
version: 3.7
description: >
             Displays Mob health in chat when damaged by players.

commands:
    MobHealth:
        description: Root command for all  MobHealth Commands.
        usage: /<command> [reload|toggle]

permissions:
    mobhealth.*:
        description: Gives access to all MobHealth commands/functions.
        children:
            mobhealth.show: true
            mobhealth.command.*: true

    mobhealth.show:
        description: Allows user to view damage notifications.
        default: true

    mobhealth.command.*:
        description: Allows user to use MobHealth commands. (Also MobHealth.commands for legacy support).
        default: op
        children:
            mobhealth.command.reload: true
            mobhealth.command.toggle: true
            mobhealth.command.toggle.others: true

    mobhealth.command.reload:
        description: Allows user to use MobHealth reload command.
        default: op

    mobhealth.command.toggle:
        description: Allows user to use MobHealth toggle command.
        default: true

    mobhealth.command.toggle.others:
        description: Allows user to toggle others with the MobHealth toggle command.
        default: op
