name: MobHealth
version: 6.1.1
description: Displays Mob health in chat when damaged by players.  Now with 100% more API!
author: SableDnah
website: http://dev.bukkit.org/server-mods/mobhealth/

main: me.sablednah.MobHealth.MobHealth
softdepend: [ Spout, Heroes, MobArena, Mobs, Likeaboss, Monster Apocalypse, ZombieMod, BloodMoon, Corruption ]

commands:
    MobHealth:
        description: Root command for all  MobHealth Commands.
        usage: /<command> [reload|toggle]

permissions:
    mobhealth.*:
        description: Gives access to all MobHealth commands/functions.
        children:
            mobhealth.show: true
            mobhealth.command.*: true

    mobhealth.show:
        description: Allows user to view damage notifications.
        default: true

    mobhealth.command.*:
        description: Allows user to use MobHealth commands.
        default: op
        children:
            mobhealth.command.reload: true
            mobhealth.command.toggle: true
            mobhealth.command.toggle.others: true

    mobhealth.command.reload:
        description: Allows user to use MobHealth reload command.
        default: op

    mobhealth.command.toggle:
        description: Allows user to use MobHealth toggle command.
        default: true

    mobhealth.command.toggle.others:
        description: Allows user to toggle others with the MobHealth toggle command.
        default: op

