name: MobHealth
main: me.sablednah.MobHealth.MobHealth
version: 2.0
description: >
             Displays Mob health in chat. Optional support for spout.
commands:
    MobHealth:
        description: All the MobHealth Commands.
        permission: <plugin name>.commands
        usage: /<command> [reload]
permissions:
    MobHealth.*:
        description: Gives access to all MobHealth commands/functions.
        children:
            MobHealth.show: true
            MobHealth.commands: true
    MobHealth.show:
        description: Allows user to view damage notifications.
        default: op
    MobHealth.commands:
        description: Allows user to use MobHealth commands.
        default: op
        